[package]
authors = ["Without Boats <woboats@gmail.com>"]
name = "failure_derive"
version = "0.1.0"

[dependencies]
quote = "0.3.15"
syn = "0.11.11"
synstructure = "0.6.0"

[dev-dependencies.failure]
git = "https://github.com/withoutboats/failure"

[lib]
proc-macro = true
